version: "3.4"

services:

  # Automação do Fluxo de dados
  nifi:
    image: "apache/nifi"
    environment:
      NIFI_WEB_HTTP_PORT: 8080   
    ports: 
      - "8090:8080"
      - "8010:8010"
    volumes:
      - ./templates/:/opt/nifi/nifi-current/conf/templates/
    restart: always 

  producer_nifi:
    build:
      context: producer/
    container_name: producer_pedido
    ports:
    - "5001:5001"
    restart: always
    environment:
      - "HOST=kafka"
      - "PORTA=9092"
      - "TOPICO=NOVO_PEDIDO"
      - "WEBHOOK=inserir_webhook"
      - "CANAL=lab-testes"
    depends_on:
      - kafka
      
  zookeeper:
    image: "confluentinc/cp-zookeeper"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181    
    ports: 
      - "2181:2181"
    restart: always      

  # usar no Nifi: PublishKafka_1_0
  kafka:
    image: "confluentinc/cp-kafka"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1      
    ports: 
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: always      
  
  # ferramenta visualização Kafka
  kowl:
    image: quay.io/cloudhut/kowl:v1.2.2
    restart: on-failure
    hostname: kowl
    ports:
    - "8070:8080"
    volumes:
    - ./kowl_config.yaml:/etc/kowl/config.yaml
    entrypoint: ./kowl --config.filepath=/etc/kowl/config.yaml
    depends_on:
      - kafka

  # exemplo MongoDB : rodando juntos só para facilitar o LAB
  mongoexpress:
    image: mongo-express
    environment:
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=fiap
      #- ME_CONFIG_MONGODB_URL=mongodb://root:fiap@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=fiap
      - ME_CONFIG_BASICAUTH_PASSWORD=fiap
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on: 
      - mongo

  mongo:
    image: mongo:latest
    #environment:
    #    - MONGO_INITDB_ROOT_USERNAME=root
    #    - MONGO_INITDB_ROOT_PASSWORD=fiap
    volumes:
      - mongodata:/data
    ports:
      - "27017:27017"

volumes:
  mongodata:
